import { createClientOnlyFn } from "@tanstack/react-start";
import { createFileRoute, Link } from "@tanstack/react-router";
import { useEffect, useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";

import { AppShell } from "@/components/app-shell";
import {
  AINotice,
  ConfidenceBadge,
  FlagBadge,
  HumanReviewLabel,
  PriorityBadge,
  SentimentBadge,
} from "@/components/badges";
import { CitationCard } from "@/components/citation-card";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Textarea } from "@/components/ui/textarea";
import {
  acceptChatAction,
  approveChatSuggestionAction,
  closeChatAction,
  escalateChatAction,
  getChatSession,
  rejectChatSuggestionAction,
  saveChatSuggestionAction,
  sendChatReplyAction,
} from "@/lib/api/support.functions";
import { generateChatCopilot } from "@/lib/api/copilot.functions";
import type { PersistedChatSuggestion } from "@/lib/support-models";
import { cn } from "@/lib/utils";
import {
  ArrowLeft,
  Check,
  ClipboardCopy,
  LoaderCircle,
  RefreshCw,
  Save,
  Send,
  ShieldAlert,
  Sparkles,
  ThumbsDown,
  ThumbsUp,
} from "lucide-react";

const loadCustomerBackendClient = createClientOnlyFn(() =>
  import("@/lib/customer-backend.client"),
);

export const Route = createFileRoute("/chat/$id")({
  head: ({ params }) => ({ meta: [{ title: `${params.id} - Live chat` }] }),
  component: ChatDetail,
  notFoundComponent: () => (
    <AppShell>
      <div className="p-10 text-center text-sm text-muted-foreground">Chat not found.</div>
    </AppShell>
  ),
});

function ChatDetail() {
  const { id } = Route.useParams();
  const queryClient = useQueryClient();
  const [composer, setComposer] = useState("");
  const [draft, setDraft] = useState("");
  const [edited, setEdited] = useState(false);
  const [pageMessage, setPageMessage] = useState<string | null>(null);
  const [autoGeneratedFor, setAutoGeneratedFor] = useState<string | null>(null);

  const sessionQuery = useQuery({
    queryKey: ["chat-session", id],
    queryFn: () => getChatSession({ data: { sessionId: id } }),
    refetchInterval: 10_000,
  });

  const sessionDetail = sessionQuery.data;
  const session = sessionDetail?.session ?? null;
  const latestSuggestion = sessionDetail?.latestSuggestion ?? null;
  const lastMessage = sessionDetail?.messages.at(-1) ?? null;

  const refreshQueries = async () => {
    await Promise.all([
      queryClient.invalidateQueries({ queryKey: ["chat-session", id] }),
      queryClient.invalidateQueries({ queryKey: ["chat-sessions"] }),
      queryClient.invalidateQueries({ queryKey: ["support-overview"] }),
    ]);
  };

  const copilotMutation = useMutation({
    mutationFn: async () => {
      if (!session) {
        throw new Error("Chat session details are not available yet.");
      }

      return generateChatCopilot({
        data: {
          conversationId: session.id,
          conversationHistory:
            sessionDetail?.messages.map((message) => ({
              sender: message.from,
              message: message.text,
            })) ?? [],
          latestMessage: lastMessage?.text ?? session.briefDescription,
          knownDetails: {
            category: session.category,
            topic: session.briefDescription,
          },
          missingDetails: [],
          customerPlan: inferCustomerPlan(session.flags),
        },
      });
    },
    onSuccess: async (result) => {
      setDraft(result.suggestion.suggestedReply);
      setEdited(false);
      setPageMessage("New AI suggestion generated.");
      await refreshQueries();
    },
  });

  const activeSuggestionId = latestSuggestion?.id ?? copilotMutation.data?.suggestionId ?? null;

  const saveMutation = useMutation({
    mutationFn: async () => {
      if (!activeSuggestionId) throw new Error("No AI suggestion is available to save.");
      return saveChatSuggestionAction({
        data: { suggestionId: activeSuggestionId, editedReply: draft.trim() },
      });
    },
    onSuccess: async () => {
      setEdited(false);
      setPageMessage("Suggestion saved.");
      await refreshQueries();
    },
  });

  const acceptMutation = useMutation({
    mutationFn: async () => {
      if (!session) throw new Error("Chat session details are not available yet.");
      return acceptChatAction({
        data: {
          sessionId: session.id,
        },
      });
    },
    onSuccess: async () => {
      setPageMessage("Chat accepted.");
      await refreshQueries();
    },
  });

  const approveMutation = useMutation({
    mutationFn: async () => {
      if (!activeSuggestionId) throw new Error("No AI suggestion is available to approve.");
      return approveChatSuggestionAction({
        data: { suggestionId: activeSuggestionId, editedReply: draft.trim() },
      });
    },
    onSuccess: async () => {
      setEdited(false);
      setPageMessage("Suggestion approved.");
      await refreshQueries();
    },
  });

  const rejectMutation = useMutation({
    mutationFn: async () => {
      if (!activeSuggestionId) throw new Error("No AI suggestion is available to reject.");
      return rejectChatSuggestionAction({
        data: { suggestionId: activeSuggestionId, note: "Rejected from the live chat UI." },
      });
    },
    onSuccess: async () => {
      setDraft("");
      setEdited(false);
      setPageMessage("Suggestion rejected.");
      await refreshQueries();
    },
  });

  const sendMutation = useMutation({
    mutationFn: async () => {
      if (!session) throw new Error("Chat session details are not available yet.");
      if (!activeSuggestionId) throw new Error("Generate a suggestion before sending.");
      if (!composer.trim()) throw new Error("Reply is empty.");

      return sendChatReplyAction({
        data: {
          suggestionId: activeSuggestionId,
          sessionId: session.id,
          message: composer.trim(),
        },
      });
    },
    onSuccess: async () => {
      setComposer("");
      setEdited(false);
      setPageMessage("Reply sent through the customer backend.");
      await refreshQueries();
    },
  });

  const closeMutation = useMutation({
    mutationFn: async () => {
      if (!session) throw new Error("Chat session details are not available yet.");
      return closeChatAction({
        data: {
          sessionId: session.id,
        },
      });
    },
    onSuccess: async () => {
      setPageMessage("Chat closed.");
      await refreshQueries();
    },
  });

  const escalateMutation = useMutation({
    mutationFn: async () => {
      if (!session) throw new Error("Chat session details are not available yet.");
      if (!activeSuggestionId) throw new Error("Generate a suggestion before escalating.");

      return escalateChatAction({
        data: {
          suggestionId: activeSuggestionId,
          sessionId: session.id,
          reason:
            latestSuggestion?.escalationReason ??
            "Escalated from the live chat UI for manual handling.",
          targetTeam: inferEscalationTeam(session.flags),
        },
      });
    },
    onSuccess: async () => {
      setPageMessage("Chat escalated.");
      await refreshQueries();
    },
  });

  useEffect(() => {
    setPageMessage(null);
    setEdited(false);
    setAutoGeneratedFor(null);
  }, [id]);

  useEffect(() => {
    setDraft(getSuggestionText(latestSuggestion));
    setEdited(false);
  }, [latestSuggestion?.id]);

  useEffect(() => {
    if (!session || latestSuggestion || autoGeneratedFor === session.id || copilotMutation.isPending) {
      return;
    }

    setAutoGeneratedFor(session.id);
    copilotMutation.mutate();
  }, [autoGeneratedFor, copilotMutation, latestSuggestion, session]);

  useEffect(() => {
    if (!session?.id) return;

    let socketCleanup: (() => void) | undefined;

    void loadCustomerBackendClient()?.then(({ createCustomerBackendSocket }) => {
      const socket = createCustomerBackendSocket();
      if (!socket) return;

      const refreshFromRealtime = (payload?: { sessionId?: string }) => {
        if (payload?.sessionId && payload.sessionId !== session.id) return;
        void refreshQueries();
      };

      socket.on("connect", () => {
        socket.emit("join_chat_session", {
          sessionId: session.id,
        });
      });
      socket.on("chat_accepted", refreshFromRealtime);
      socket.on("chat_closed", refreshFromRealtime);
      socket.on("receive_message", refreshFromRealtime);

      socket.connect();

      socketCleanup = () => {
        socket.removeAllListeners();
        socket.disconnect();
      };
    });

    return () => {
      socketCleanup?.();
    };
  }, [session?.id]);

  const analysis = latestSuggestion?.analysisSnapshot ?? copilotMutation.data?.analysis ?? null;
  const currentPriority = toUiPriority(analysis?.priority ?? session?.priority ?? "Medium");
  const currentSentiment = toUiSentiment(analysis?.sentiment ?? session?.sentiment ?? "Neutral");
  const currentCategory = analysis?.category ?? session?.category ?? "Support";
  const currentConfidence =
    latestSuggestion?.confidence ?? analysis?.confidence ?? session?.confidence ?? 0;
  const humanOnly = Boolean(
    session?.flags.some((flag) => ["security_issue", "vip_customer", "low_confidence"].includes(flag)) ||
      latestSuggestion?.escalationRequired ||
      sessionDetail?.escalations.some((entry) => entry.status !== "resolved" && entry.status !== "closed"),
  );

  const firstOpenEscalation = useMemo(
    () =>
      sessionDetail?.escalations.find((entry) => entry.status !== "resolved" && entry.status !== "closed") ?? null,
    [sessionDetail?.escalations],
  );
  const canAcceptChat = session?.status === "waiting";
  const canCloseChat = session?.status !== "ended";

  const activeError =
    sessionQuery.error ??
    copilotMutation.error ??
    saveMutation.error ??
    acceptMutation.error ??
    approveMutation.error ??
    rejectMutation.error ??
    sendMutation.error ??
    closeMutation.error ??
    escalateMutation.error;

  const isBusy =
    copilotMutation.isPending ||
    saveMutation.isPending ||
    acceptMutation.isPending ||
    approveMutation.isPending ||
    rejectMutation.isPending ||
    sendMutation.isPending ||
    closeMutation.isPending ||
    escalateMutation.isPending;

  if (sessionQuery.isLoading) {
    return (
      <AppShell>
        <div className="flex items-center gap-2 p-6 text-sm text-muted-foreground">
          <LoaderCircle className="h-4 w-4 animate-spin" />
          Loading chat session...
        </div>
      </AppShell>
    );
  }

  if (!session) {
    return (
      <AppShell>
        <div className="p-10 text-center text-sm text-muted-foreground">Chat not found.</div>
      </AppShell>
    );
  }

  return (
    <AppShell>
      <div className="grid h-[calc(100vh-57px)] grid-cols-[1fr_420px]">
        <div className="flex min-h-0 flex-col border-r border-border bg-surface-elevated">
          <div className="flex items-center justify-between border-b border-border bg-surface px-6 py-3">
            <div className="flex items-center gap-3">
              <Link
                to="/chat"
                className="grid h-8 w-8 place-items-center rounded-md border border-border hover:bg-muted"
              >
                <ArrowLeft className="h-4 w-4" />
              </Link>
              <div className="grid h-9 w-9 place-items-center rounded-full bg-accent text-xs font-semibold text-accent-foreground">
                {session.customerName
                  .split(" ")
                  .map((part) => part[0])
                  .slice(0, 2)
                  .join("")}
              </div>
              <div>
                <div className="text-sm font-semibold">{session.customerName}</div>
                <div className="flex items-center gap-2 text-[11px] text-muted-foreground">
                  <span className="font-mono">{session.id}</span>
                  <span className="font-mono">-</span>
                  <span>{session.category}</span>
                  <span className="inline-flex items-center gap-1">
                    <span className="h-1.5 w-1.5 rounded-full bg-success" />
                    {session.status}
                  </span>
                </div>
              </div>
            </div>
            <div className="flex items-center gap-1.5">
              {canAcceptChat && (
                <Button size="sm" variant="outline" onClick={() => acceptMutation.mutate()} disabled={isBusy}>
                  {acceptMutation.isPending ? (
                    <LoaderCircle className="mr-1.5 h-3.5 w-3.5 animate-spin" />
                  ) : (
                    <Check className="mr-1.5 h-3.5 w-3.5" />
                  )}
                  Accept chat
                </Button>
              )}
              {canCloseChat && (
                <Button size="sm" variant="outline" onClick={() => closeMutation.mutate()} disabled={isBusy}>
                  {closeMutation.isPending ? (
                    <LoaderCircle className="mr-1.5 h-3.5 w-3.5 animate-spin" />
                  ) : (
                    <ShieldAlert className="mr-1.5 h-3.5 w-3.5" />
                  )}
                  Close chat
                </Button>
              )}
              <PriorityBadge value={currentPriority} />
              <SentimentBadge value={currentSentiment} />
              {session.flags.map((flag) => (
                <FlagBadge key={flag} flag={flag} />
              ))}
            </div>
          </div>

          {pageMessage && (
            <div className="border-b border-success/30 bg-success/10 px-6 py-2 text-sm text-success">
              {pageMessage}
            </div>
          )}
          {activeError && (
            <div className="border-b border-danger/30 bg-danger/10 px-6 py-2 text-sm text-danger">
              {activeError.message}
            </div>
          )}
          {humanOnly && (
            <div className="border-b border-danger/30 bg-danger/10 px-6 py-3">
              <div className="flex items-center gap-2 text-sm">
                <ShieldAlert className="h-4 w-4 text-danger" />
                <span className="font-semibold text-danger">Human review required</span>
                <span className="text-muted-foreground">
                  {firstOpenEscalation?.reason ??
                    latestSuggestion?.escalationReason ??
                    "Treat this conversation as high-risk."}
                </span>
                <HumanReviewLabel className="ml-auto" />
              </div>
            </div>
          )}

          <div className="flex-1 space-y-3 overflow-y-auto px-6 py-5">
            {sessionDetail?.messages.map((message) => {
              const isCustomer = message.from === "customer";
              return (
                <div key={message.id} className={`flex ${isCustomer ? "" : "justify-end"}`}>
                  <div
                    className={`max-w-[75%] rounded-2xl px-4 py-2.5 text-sm shadow-sm ${
                      isCustomer
                        ? "rounded-tl-sm border border-border bg-surface"
                        : "rounded-tr-sm bg-primary text-primary-foreground"
                    }`}
                  >
                    <p className="whitespace-pre-line">{message.text}</p>
                    <div
                      className={`mt-1 text-[10px] ${
                        isCustomer ? "text-muted-foreground" : "text-primary-foreground/70"
                      }`}
                    >
                      {formatTimestamp(message.at)}
                    </div>
                  </div>
                </div>
              );
            })}
          </div>

          <div className="border-t border-border bg-surface p-4">
            <div className="rounded-xl border border-border bg-surface-elevated p-2 focus-within:border-primary/50">
              <Textarea
                value={composer}
                onChange={(event) => setComposer(event.target.value)}
                placeholder="Reply to customer..."
                className="min-h-[60px] resize-none border-0 bg-transparent p-2 shadow-none focus-visible:ring-0"
              />
              <div className="flex items-center justify-between gap-2 px-1 pt-1">
                <div className="flex items-center gap-1.5">
                  <Button size="sm" variant="ghost" onClick={() => setComposer(draft)} disabled={!draft}>
                    <Sparkles className="mr-1.5 h-3.5 w-3.5 text-ai" /> Insert AI draft
                  </Button>
                  <Button
                    size="sm"
                    variant="ghost"
                    onClick={async () => {
                      await navigator.clipboard.writeText(draft);
                      setPageMessage("Suggestion copied to clipboard.");
                    }}
                    disabled={!draft}
                  >
                    <ClipboardCopy className="mr-1.5 h-3.5 w-3.5" /> Copy
                  </Button>
                </div>
                <Button size="sm" onClick={() => sendMutation.mutate()} disabled={!composer.trim() || isBusy || !activeSuggestionId}>
                  <Send className="mr-1.5 h-3.5 w-3.5" /> Send
                </Button>
              </div>
            </div>
            <div className="mt-2 flex items-center justify-between text-[11px] text-muted-foreground">
              <span>Messages are sent through the customer backend Socket.IO flow.</span>
              <span className="inline-flex items-center gap-1">
                <ShieldAlert className="h-3 w-3" /> AI steps run server-side
              </span>
            </div>
          </div>
        </div>

        <aside className="flex min-h-0 flex-col bg-background">
          <div className="border-b border-border bg-surface px-5 py-3">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <div className="grid h-7 w-7 place-items-center rounded-md bg-gradient-to-br from-ai to-primary">
                  <Sparkles className="h-3.5 w-3.5 text-ai-foreground" />
                </div>
                <div>
                  <div className="text-sm font-semibold">Live AI assist</div>
                  <div className="text-[11px] text-muted-foreground">
                    Persisted classification, retrieval, suggestion, and review state
                  </div>
                </div>
              </div>
              <ConfidenceBadge value={currentConfidence} />
            </div>
          </div>

          <div className="flex-1 space-y-4 overflow-y-auto p-5">
            <Card className="border-2 border-ai/30 shadow-sm">
              <CardContent className="p-0">
                <div className="flex items-center justify-between border-b border-border bg-ai-soft px-4 py-2.5">
                  <div className="flex items-center gap-2 text-xs">
                    <Sparkles className="h-3.5 w-3.5 text-ai" />
                    <span className="font-semibold text-ai">Suggested reply</span>
                  </div>
                  <Button
                    size="sm"
                    variant="ghost"
                    className="h-7 px-2 text-xs"
                    onClick={() => copilotMutation.mutate()}
                    disabled={isBusy}
                  >
                    {copilotMutation.isPending ? (
                      <LoaderCircle className="mr-1 h-3 w-3 animate-spin" />
                    ) : (
                      <RefreshCw className="mr-1 h-3 w-3" />
                    )}
                    Regen
                  </Button>
                </div>
                <div className="p-4">
                  {copilotMutation.isPending && !draft ? (
                    <div className="flex min-h-[140px] items-center justify-center text-sm text-muted-foreground">
                      <LoaderCircle className="mr-2 h-4 w-4 animate-spin" />
                      Generating suggestion...
                    </div>
                  ) : (
                    <Textarea
                      value={draft}
                      onChange={(event) => {
                        setDraft(event.target.value);
                        setEdited(true);
                      }}
                      className="min-h-[140px] border-0 bg-transparent p-0 text-sm leading-relaxed shadow-none focus-visible:ring-0"
                    />
                  )}
                  <div className="mt-3 flex items-center justify-between">
                    <div className="flex items-center gap-2">
                      <AINotice />
                      {humanOnly && <HumanReviewLabel />}
                    </div>
                    <div className="flex items-center gap-1">
                      <button
                        className="grid h-7 w-7 place-items-center rounded-md border border-border hover:bg-muted"
                        title="Approve suggestion"
                        onClick={() => approveMutation.mutate()}
                        disabled={isBusy || !activeSuggestionId || !draft.trim()}
                      >
                        <ThumbsUp className="h-3.5 w-3.5" />
                      </button>
                      <button
                        className="grid h-7 w-7 place-items-center rounded-md border border-border hover:bg-muted"
                        title="Reject suggestion"
                        onClick={() => rejectMutation.mutate()}
                        disabled={isBusy || !activeSuggestionId}
                      >
                        <ThumbsDown className="h-3.5 w-3.5" />
                      </button>
                    </div>
                  </div>
                  {edited && (
                    <div className="mt-2 text-[11px] text-muted-foreground">
                      Local edits are ready to save, approve, or send.
                    </div>
                  )}
                  <div className="mt-3 flex flex-wrap gap-2">
                    <Button size="sm" variant="outline" onClick={() => saveMutation.mutate()} disabled={isBusy || !activeSuggestionId || !draft.trim()}>
                      <Save className="mr-1.5 h-3.5 w-3.5" /> Save
                    </Button>
                    <Button size="sm" variant="outline" onClick={() => setComposer(draft)} disabled={!draft}>
                      <Check className="mr-1.5 h-3.5 w-3.5" /> Use this reply
                    </Button>
                    <Button size="sm" variant="outline" onClick={() => escalateMutation.mutate()} disabled={isBusy || !activeSuggestionId}>
                      <ShieldAlert className="mr-1.5 h-3.5 w-3.5" /> Escalate
                    </Button>
                  </div>
                </div>
              </CardContent>
            </Card>

            <Card>
              <CardContent className="p-4">
                <div className="mb-2 text-[11px] font-semibold uppercase tracking-wider text-muted-foreground">
                  Agent notes
                </div>
                <p className="text-sm text-foreground/90">
                  {latestSuggestion?.agentNotes || "Waiting for suggestion details."}
                </p>
                {latestSuggestion?.missingInfo?.length ? (
                  <div className="mt-3 flex flex-wrap gap-1.5">
                    {latestSuggestion.missingInfo.map((item) => (
                      <span
                        key={item}
                        className="rounded-md border border-warning/40 bg-warning/10 px-2 py-1 text-[11px] font-semibold text-warning-foreground"
                      >
                        {item}
                      </span>
                    ))}
                  </div>
                ) : null}
              </CardContent>
            </Card>

            <Card>
              <CardContent className="p-4">
                <div className="mb-2 text-[11px] font-semibold uppercase tracking-wider text-muted-foreground">
                  Sources used
                </div>
                <div className="mb-3 text-xs text-muted-foreground">
                  Query: {latestSuggestion?.sourceQuery ?? copilotMutation.data?.searchQuery ?? "Running retrieval"}
                </div>
                <div className="space-y-2">
                  {(latestSuggestion?.sourceSnapshot ?? copilotMutation.data?.sources ?? []).map((source) => (
                    <CitationCard key={source.id} source={source} relevance={source.relevance} />
                  ))}
                  {!latestSuggestion?.sourceSnapshot?.length && !copilotMutation.data?.sources?.length && (
                    <div className="rounded-md border border-dashed border-border p-4 text-sm text-muted-foreground">
                      No sources were returned for this conversation yet.
                    </div>
                  )}
                </div>
              </CardContent>
            </Card>

            <Card>
              <CardContent className="p-4">
                <div className="mb-2 text-[11px] font-semibold uppercase tracking-wider text-muted-foreground">
                  Conversation facts
                </div>
                <div className="space-y-1.5 text-xs">
                  <EntityRow label="Customer tier" value={inferCustomerPlan(session.flags)} />
                  <EntityRow label="Detected category" value={currentCategory} />
                  <EntityRow label="Detected priority" value={currentPriority} />
                  <EntityRow label="Detected sentiment" value={currentSentiment} />
                  <EntityRow label="Missing info" value={formatMissingInfo(latestSuggestion?.missingInfo)} />
                </div>
                {analysis && (
                  <>
                    <div className="mt-4 grid grid-cols-2 gap-3">
                      <ScorePill label="Category" value={analysis.confidenceBreakdown.category} />
                      <ScorePill label="Priority" value={analysis.confidenceBreakdown.priority} />
                      <ScorePill label="Sentiment" value={analysis.confidenceBreakdown.sentiment} />
                      <ScorePill label="Entities" value={analysis.confidenceBreakdown.entity} />
                    </div>
                    <div className="mt-4 space-y-1.5">
                      {Object.entries(analysis.entities).length > 0 ? (
                        Object.entries(analysis.entities).map(([key, value]) => (
                          <EntityRow key={key} label={key.replaceAll("_", " ")} value={value} />
                        ))
                      ) : (
                        <div className="text-sm text-muted-foreground">
                          No entities extracted from the latest customer message.
                        </div>
                      )}
                    </div>
                  </>
                )}
              </CardContent>
            </Card>
          </div>
        </aside>
      </div>
    </AppShell>
  );
}

function EntityRow({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex items-center justify-between gap-4">
      <span className="text-muted-foreground">{label}</span>
      <span className="font-mono text-right">{value}</span>
    </div>
  );
}

function ScorePill({ label, value }: { label: string; value: number }) {
  return (
    <div className="rounded-md border border-border bg-surface/70 px-3 py-2">
      <div className="text-[11px] uppercase tracking-wide text-muted-foreground">{label}</div>
      <div className="mt-1 text-sm font-semibold">{Math.round(value * 100)}%</div>
    </div>
  );
}

function getSuggestionText(suggestion: PersistedChatSuggestion | null) {
  return suggestion?.editedReply ?? suggestion?.generatedReply ?? "";
}

function inferCustomerPlan(flags: string[]) {
  return flags.includes("vip_customer") ? "enterprise" : "standard";
}

function inferEscalationTeam(flags: string[]) {
  if (flags.includes("security_issue")) return "security";
  if (flags.includes("payment_dispute")) return "billing";
  return "tier-2";
}

function formatMissingInfo(values?: string[]) {
  if (!values?.length) return "none";
  return values.map((value) => value.replaceAll("_", " ")).join(", ");
}

function formatTimestamp(value: string) {
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return "--";
  return new Intl.DateTimeFormat("en-US", {
    month: "short",
    day: "numeric",
    hour: "numeric",
    minute: "2-digit",
  }).format(date);
}

function toUiPriority(value: string) {
  const normalized = value.toLowerCase();
  if (normalized === "urgent") return "Urgent" as const;
  if (normalized === "high") return "High" as const;
  if (normalized === "low") return "Low" as const;
  return "Medium" as const;
}

function toUiSentiment(value: string) {
  const normalized = value.toLowerCase();
  if (normalized === "angry") return "Angry" as const;
  if (normalized === "frustrated") return "Frustrated" as const;
  if (normalized === "confused") return "Confused" as const;
  return "Neutral" as const;
}
