import { createClientOnlyFn } from "@tanstack/react-start";
import { createFileRoute, Link } from "@tanstack/react-router";
import { useEffect, useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";

import { AppShell } from "@/components/app-shell";
import {
  AINotice,
  ConfidenceBadge,
  FlagBadge,
  HumanReviewLabel,
  PriorityBadge,
  SentimentBadge,
  StatusBadge,
} from "@/components/badges";
import { CitationCard } from "@/components/citation-card";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Textarea } from "@/components/ui/textarea";
import {
  acceptTicketAction,
  approveTicketDraftAction,
  escalateTicketAction,
  getSupportTicket,
  rejectTicketDraftAction,
  saveTicketDraftAction,
  sendTicketReplyAction,
} from "@/lib/api/support.functions";
import { generateTicketCopilot } from "@/lib/api/copilot.functions";
import type { PersistedTicketDraft } from "@/lib/support-models";
import { cn } from "@/lib/utils";
import {
  AlertTriangle,
  ArrowLeft,
  Check,
  ClipboardCopy,
  LoaderCircle,
  RefreshCw,
  Save,
  Send,
  ShieldAlert,
  Sparkles,
  Tag,
  User,
  Workflow,
  X,
} from "lucide-react";

const loadCustomerBackendClient = createClientOnlyFn(() =>
  import("@/lib/customer-backend.client"),
);

export const Route = createFileRoute("/tickets/$id")({
  head: ({ params }) => ({ meta: [{ title: `${params.id} - Sentinel Copilot` }] }),
  component: TicketDetail,
  notFoundComponent: () => (
    <AppShell>
      <div className="p-10 text-center text-sm text-muted-foreground">Ticket not found.</div>
    </AppShell>
  ),
});

function TicketDetail() {
  const { id } = Route.useParams();
  const queryClient = useQueryClient();
  const [draft, setDraft] = useState("");
  const [edited, setEdited] = useState(false);
  const [pageMessage, setPageMessage] = useState<string | null>(null);
  const [autoGeneratedFor, setAutoGeneratedFor] = useState<string | null>(null);

  const ticketQuery = useQuery({
    queryKey: ["support-ticket", id],
    queryFn: () => getSupportTicket({ data: { ticketId: id } }),
    refetchInterval: 10_000,
  });

  const ticketDetail = ticketQuery.data;
  const ticket = ticketDetail?.ticket ?? null;
  const latestDraft = ticketDetail?.latestDraft ?? null;

  const refreshQueries = async () => {
    await Promise.all([
      queryClient.invalidateQueries({ queryKey: ["support-ticket", id] }),
      queryClient.invalidateQueries({ queryKey: ["support-tickets"] }),
      queryClient.invalidateQueries({ queryKey: ["support-overview"] }),
    ]);
  };

  const copilotMutation = useMutation({
    mutationFn: async () => {
      if (!ticket) {
        throw new Error("Ticket details are not available yet.");
      }

      return generateTicketCopilot({
        data: {
          ticketId: ticket.id,
          trackingCode: ticket.trackingCode,
          subject: ticket.subject,
          customerMessage: ticket.description,
          channel: "email",
          customerPlan: inferCustomerPlan(ticket.flags),
          createdAt: ticket.createdAt,
        },
      });
    },
    onSuccess: async (result) => {
      setDraft(result.draft.replyDraft);
      setEdited(false);
      setPageMessage("New AI draft generated.");
      await refreshQueries();
    },
  });

  const activeDraftId = latestDraft?.id ?? copilotMutation.data?.draftId ?? null;

  const saveMutation = useMutation({
    mutationFn: async () => {
      if (!activeDraftId) throw new Error("No AI draft is available to save.");
      return saveTicketDraftAction({ data: { draftId: activeDraftId, editedReply: draft.trim() } });
    },
    onSuccess: async () => {
      setEdited(false);
      setPageMessage("Draft saved.");
      await refreshQueries();
    },
  });

  const acceptMutation = useMutation({
    mutationFn: async () => {
      if (!ticket) throw new Error("Ticket details are not available yet.");
      return acceptTicketAction({
        data: {
          ticketId: ticket.id,
          trackingCode: ticket.trackingCode,
        },
      });
    },
    onSuccess: async () => {
      setPageMessage("Ticket accepted.");
      await refreshQueries();
    },
  });

  const approveMutation = useMutation({
    mutationFn: async () => {
      if (!activeDraftId) throw new Error("No AI draft is available to approve.");
      return approveTicketDraftAction({ data: { draftId: activeDraftId, editedReply: draft.trim() } });
    },
    onSuccess: async () => {
      setEdited(false);
      setPageMessage("Draft approved.");
      await refreshQueries();
    },
  });

  const rejectMutation = useMutation({
    mutationFn: async () => {
      if (!activeDraftId) throw new Error("No AI draft is available to reject.");
      return rejectTicketDraftAction({
        data: { draftId: activeDraftId, note: "Rejected from the ticket review UI." },
      });
    },
    onSuccess: async () => {
      setDraft("");
      setEdited(false);
      setPageMessage("Draft rejected.");
      await refreshQueries();
    },
  });

  const sendMutation = useMutation({
    mutationFn: async () => {
      if (!ticket) throw new Error("Ticket details are not available yet.");
      if (!activeDraftId) throw new Error("No AI draft is available to send.");
      if (!draft.trim()) throw new Error("Draft is empty.");

      return sendTicketReplyAction({
        data: {
          draftId: activeDraftId,
          ticketId: ticket.id,
          trackingCode: ticket.trackingCode,
          message: draft.trim(),
        },
      });
    },
    onSuccess: async () => {
      setEdited(false);
      setPageMessage("Reply sent through the customer backend.");
      await refreshQueries();
    },
  });

  const escalateMutation = useMutation({
    mutationFn: async () => {
      if (!ticket) throw new Error("Ticket details are not available yet.");
      if (!activeDraftId) throw new Error("Generate a draft before escalating.");

      return escalateTicketAction({
        data: {
          draftId: activeDraftId,
          ticketId: ticket.id,
          reason:
            latestDraft?.escalationReason ??
            "Escalated from the ticket review UI for manual follow-up.",
          targetTeam: inferEscalationTeam(ticket.flags),
        },
      });
    },
    onSuccess: async () => {
      setPageMessage("Ticket escalated.");
      await refreshQueries();
    },
  });

  useEffect(() => {
    setPageMessage(null);
    setEdited(false);
    setAutoGeneratedFor(null);
  }, [id]);

  useEffect(() => {
    setDraft(getDraftText(latestDraft));
    setEdited(false);
  }, [latestDraft?.id]);

  useEffect(() => {
    if (!ticket || latestDraft || autoGeneratedFor === ticket.id || copilotMutation.isPending) {
      return;
    }

    setAutoGeneratedFor(ticket.id);
    copilotMutation.mutate();
  }, [autoGeneratedFor, copilotMutation, latestDraft, ticket]);

  useEffect(() => {
    if (!ticket?.trackingCode) return;

    let socketCleanup: (() => void) | undefined;

    void loadCustomerBackendClient()?.then(({ createCustomerBackendSocket }) => {
      const socket = createCustomerBackendSocket();
      if (!socket) return;

      const refreshFromRealtime = (payload?: { trackingCode?: string }) => {
        if (payload?.trackingCode && payload.trackingCode !== ticket.trackingCode) return;
        void refreshQueries();
      };

      socket.on("connect", () => {
        socket.emit("join_ticket_tracking", {
          trackingCode: ticket.trackingCode,
        });
      });
      socket.on("ticket_accepted", refreshFromRealtime);
      socket.on("ticket_status_updated", refreshFromRealtime);
      socket.on("ticket_reply", refreshFromRealtime);

      socket.connect();

      socketCleanup = () => {
        socket.removeAllListeners();
        socket.disconnect();
      };
    });

    return () => {
      socketCleanup?.();
    };
  }, [ticket?.trackingCode]);

  const analysis = latestDraft?.analysisSnapshot ?? copilotMutation.data?.analysis ?? null;
  const sources = latestDraft?.sourceSnapshot ?? copilotMutation.data?.sources ?? [];
  const currentPriority = toUiPriority(analysis?.priority ?? ticket?.priority ?? "Medium");
  const currentSentiment = toUiSentiment(analysis?.sentiment ?? ticket?.sentiment ?? "Neutral");
  const currentCategory = analysis?.category ?? ticket?.category ?? "Support";
  const currentConfidence = latestDraft?.confidence ?? analysis?.confidence ?? ticket?.confidence ?? 0;
  const humanOnly = Boolean(
    ticket?.flags.some((flag) => ["security_issue", "vip_customer", "low_confidence"].includes(flag)) ||
      latestDraft?.escalationRequired ||
      ticketDetail?.escalations.some((entry) => entry.status !== "resolved" && entry.status !== "closed"),
  );

  const firstOpenEscalation = useMemo(
    () =>
      ticketDetail?.escalations.find((entry) => entry.status !== "resolved" && entry.status !== "closed") ?? null,
    [ticketDetail?.escalations],
  );
  const canAcceptTicket =
    !ticket?.assignedAgentId && ticket?.acceptedAt == null && ticket?.status !== "Resolved";

  const activeError =
    ticketQuery.error ??
    copilotMutation.error ??
    saveMutation.error ??
    acceptMutation.error ??
    approveMutation.error ??
    rejectMutation.error ??
    sendMutation.error ??
    escalateMutation.error;

  const isBusy =
    copilotMutation.isPending ||
    saveMutation.isPending ||
    acceptMutation.isPending ||
    approveMutation.isPending ||
    rejectMutation.isPending ||
    sendMutation.isPending ||
    escalateMutation.isPending;

  if (ticketQuery.isLoading) {
    return (
      <AppShell>
        <div className="flex items-center gap-2 p-6 text-sm text-muted-foreground">
          <LoaderCircle className="h-4 w-4 animate-spin" />
          Loading ticket...
        </div>
      </AppShell>
    );
  }

  if (!ticket) {
    return (
      <AppShell>
        <div className="p-10 text-center text-sm text-muted-foreground">Ticket not found.</div>
      </AppShell>
    );
  }

  return (
    <AppShell>
      <div className="border-b border-border bg-surface px-6 py-4">
        <Link
          to="/tickets"
          className="inline-flex items-center gap-1.5 text-xs text-muted-foreground hover:text-foreground"
        >
          <ArrowLeft className="h-3.5 w-3.5" /> Back to tickets
        </Link>
        <div className="mt-2 flex flex-wrap items-end justify-between gap-3">
          <div>
            <div className="flex items-center gap-2 text-xs">
              <span className="font-mono text-muted-foreground">{ticket.trackingCode}</span>
              <span className="text-muted-foreground">-</span>
              <span className="text-muted-foreground">{currentCategory}</span>
            </div>
            <h1 className="mt-1 text-xl font-semibold tracking-tight">{ticket.subject}</h1>
          </div>
          <div className="flex flex-wrap items-center gap-1.5">
            {canAcceptTicket && (
              <Button size="sm" variant="outline" onClick={() => acceptMutation.mutate()} disabled={isBusy}>
                {acceptMutation.isPending ? (
                  <LoaderCircle className="mr-1.5 h-3.5 w-3.5 animate-spin" />
                ) : (
                  <Check className="mr-1.5 h-3.5 w-3.5" />
                )}
                Accept ticket
              </Button>
            )}
            <PriorityBadge value={currentPriority} />
            <SentimentBadge value={currentSentiment} />
            <StatusBadge value={ticket.status} />
            <ConfidenceBadge value={currentConfidence} />
          </div>
        </div>
        {ticket.flags.length > 0 && (
          <div className="mt-3 flex flex-wrap gap-1.5">
            {ticket.flags.map((flag) => (
              <FlagBadge key={flag} flag={flag} />
            ))}
            {humanOnly && <HumanReviewLabel />}
          </div>
        )}
      </div>

      <div className="grid grid-cols-1 gap-6 p-6 xl:grid-cols-[1fr_360px]">
        <div className="space-y-6">
          {pageMessage && (
            <div className="rounded-md border border-success/30 bg-success/10 px-3 py-2 text-sm text-success">
              {pageMessage}
            </div>
          )}
          {activeError && (
            <div className="rounded-md border border-danger/30 bg-danger/10 px-3 py-2 text-sm text-danger">
              {activeError.message}
            </div>
          )}

          {humanOnly && (
            <Card className="border-danger/40 bg-danger/5">
              <CardContent className="flex items-start gap-3 p-4">
                <ShieldAlert className="mt-0.5 h-5 w-5 text-danger" />
                <div className="text-sm">
                  <div className="font-semibold text-danger">Escalation or human review required</div>
                  <div className="text-muted-foreground">
                    {firstOpenEscalation?.reason ??
                      latestDraft?.escalationReason ??
                      "This ticket should be reviewed by an agent before a reply is sent."}
                  </div>
                </div>
              </CardContent>
            </Card>
          )}

          <Card>
            <CardContent className="p-0">
              <div className="border-b border-border px-5 py-3 text-xs font-semibold uppercase tracking-wider text-muted-foreground">
                Conversation
              </div>
              <div className="divide-y divide-border">
                {ticketDetail?.replies.map((message) => (
                  <Message key={message.id} message={message} customerName={ticket.customerName} />
                ))}
              </div>
            </CardContent>
          </Card>

          <Card className="ai-gradient border-ai/30">
            <CardContent className="p-5">
              <div className="mb-3 flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <div className="grid h-7 w-7 place-items-center rounded-md bg-ai text-ai-foreground">
                    <Sparkles className="h-3.5 w-3.5" />
                  </div>
                  <div>
                    <div className="text-sm font-semibold">AI analysis</div>
                    <div className="text-[11px] text-muted-foreground">
                      Real member 1 classification plus member 2 retrieval and member 3 drafting
                    </div>
                  </div>
                </div>
                <ConfidenceBadge value={currentConfidence} />
              </div>
              <dl className="grid grid-cols-1 gap-3 text-sm md:grid-cols-2">
                <Field icon={Tag} label="Detected category" value={currentCategory} />
                <Field
                  icon={Workflow}
                  label="Knowledge query"
                  value={latestDraft?.sourceQuery ?? copilotMutation.data?.searchQuery ?? "Running retrieval"}
                />
                <Field icon={User} label="Customer plan" value={inferCustomerPlan(ticket.flags)} />
                <Field icon={AlertTriangle} label="Missing information" value={formatMissingInfo(latestDraft?.missingInfo)} />
              </dl>
              {analysis && (
                <div className="mt-4 grid grid-cols-2 gap-3 md:grid-cols-4">
                  <ScorePill label="Category" value={analysis.confidenceBreakdown.category} />
                  <ScorePill label="Priority" value={analysis.confidenceBreakdown.priority} />
                  <ScorePill label="Sentiment" value={analysis.confidenceBreakdown.sentiment} />
                  <ScorePill label="Entities" value={analysis.confidenceBreakdown.entity} />
                </div>
              )}
            </CardContent>
          </Card>

          <Card className="border-2 border-primary/30 shadow-sm">
            <CardContent className="p-0">
              <div className="flex items-center justify-between border-b border-border bg-surface-elevated px-5 py-3">
                <div className="flex items-center gap-2">
                  <Sparkles className="h-4 w-4 text-ai" />
                  <span className="text-sm font-semibold">Proposed reply</span>
                  <AINotice />
                  {humanOnly && <HumanReviewLabel />}
                </div>
                <div className="flex items-center gap-1.5">
                  <Button variant="ghost" size="sm" onClick={() => copilotMutation.mutate()} disabled={isBusy}>
                    {copilotMutation.isPending ? (
                      <LoaderCircle className="mr-1.5 h-3.5 w-3.5 animate-spin" />
                    ) : (
                      <RefreshCw className="mr-1.5 h-3.5 w-3.5" />
                    )}
                    Regenerate
                  </Button>
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={async () => {
                      await navigator.clipboard.writeText(draft);
                      setPageMessage("Draft copied to clipboard.");
                    }}
                    disabled={!draft}
                  >
                    <ClipboardCopy className="mr-1.5 h-3.5 w-3.5" />
                    Copy
                  </Button>
                </div>
              </div>
              <div className="p-5">
                {copilotMutation.isPending && !draft ? (
                  <div className="flex min-h-[260px] items-center justify-center text-sm text-muted-foreground">
                    <LoaderCircle className="mr-2 h-4 w-4 animate-spin" />
                    Generating grounded draft...
                  </div>
                ) : (
                  <Textarea
                    value={draft}
                    onChange={(event) => {
                      setDraft(event.target.value);
                      setEdited(true);
                    }}
                    className="min-h-[260px] font-sans text-sm leading-relaxed"
                    placeholder="The AI-generated reply will appear here."
                  />
                )}
                {edited && (
                  <div className="mt-2 text-[11px] text-muted-foreground">
                    Local edits are ready to save, approve, or send.
                  </div>
                )}
              </div>
              <div className="flex flex-wrap items-center justify-between gap-2 border-t border-border bg-surface-elevated px-5 py-3">
                <div className="flex flex-wrap items-center gap-1.5">
                  <Button
                    variant="ghost"
                    size="sm"
                    className="text-danger hover:text-danger"
                    onClick={() => {
                      setDraft("");
                      setEdited(false);
                    }}
                  >
                    <X className="mr-1.5 h-3.5 w-3.5" /> Clear
                  </Button>
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={() => {
                      setDraft(getDraftText(latestDraft));
                      setEdited(false);
                    }}
                    disabled={!latestDraft}
                  >
                    <Check className="mr-1.5 h-3.5 w-3.5" /> Restore AI draft
                  </Button>
                  <Button variant="outline" size="sm" onClick={() => saveMutation.mutate()} disabled={!draft.trim() || isBusy || !activeDraftId}>
                    <Save className="mr-1.5 h-3.5 w-3.5" /> Save
                  </Button>
                  <Button variant="outline" size="sm" onClick={() => approveMutation.mutate()} disabled={!draft.trim() || isBusy || !activeDraftId}>
                    <Check className="mr-1.5 h-3.5 w-3.5" /> Approve
                  </Button>
                  <Button
                    variant="outline"
                    size="sm"
                    className="text-danger hover:text-danger"
                    onClick={() => rejectMutation.mutate()}
                    disabled={isBusy || !activeDraftId}
                  >
                    <X className="mr-1.5 h-3.5 w-3.5" /> Reject
                  </Button>
                </div>
                <div className="flex flex-wrap items-center gap-2">
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={() => escalateMutation.mutate()}
                    disabled={isBusy || !activeDraftId}
                  >
                    <ShieldAlert className="mr-1.5 h-3.5 w-3.5" /> Escalate
                  </Button>
                  <Button size="sm" onClick={() => sendMutation.mutate()} disabled={!draft.trim() || isBusy || !activeDraftId}>
                    <Send className="mr-1.5 h-3.5 w-3.5" /> Approve and send
                  </Button>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>

        <div className="space-y-6">
          <Card>
            <CardContent className="p-5">
              <div className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">
                Ticket summary
              </div>
              <div className="mt-3 space-y-2 text-sm">
                <SummaryRow label="Customer" value={ticket.customerName} />
                <SummaryRow label="Tracking code" value={ticket.trackingCode} mono />
                <SummaryRow label="Created" value={formatTimestamp(ticket.createdAt)} />
                <SummaryRow label="Updated" value={formatTimestamp(ticket.updatedAt)} />
                <SummaryRow label="Assigned agent" value={ticket.assignedAgentId ?? "Unassigned"} mono={Boolean(ticket.assignedAgentId)} />
                <SummaryRow label="Plan" value={inferCustomerPlan(ticket.flags)} />
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardContent className="p-5">
              <div className="mb-3 flex items-center justify-between">
                <div className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">
                  Agent notes
                </div>
                {latestDraft?.missingInfo?.length ? (
                  <span className="text-[11px] text-muted-foreground">
                    {latestDraft.missingInfo.length} missing fields
                  </span>
                ) : null}
              </div>
              <p className="text-sm text-foreground/90">
                {latestDraft?.agentNotes || "Waiting for the latest AI draft."}
              </p>
              {latestDraft?.missingInfo?.length ? (
                <div className="mt-3 flex flex-wrap gap-1.5">
                  {latestDraft.missingInfo.map((item) => (
                    <span
                      key={item}
                      className="rounded-md border border-warning/40 bg-warning/10 px-2 py-1 text-[11px] font-semibold text-warning-foreground"
                    >
                      {item}
                    </span>
                  ))}
                </div>
              ) : null}
            </CardContent>
          </Card>

          <Card>
            <CardContent className="p-5">
              <div className="mb-3 flex items-center justify-between">
                <div className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">
                  Extracted entities
                </div>
                <span className="text-[11px] text-muted-foreground">{analysis?.entityCount ?? 0} found</span>
              </div>
              {analysis && Object.keys(analysis.entities).length > 0 ? (
                <div className="space-y-2">
                  {Object.entries(analysis.entities).map(([key, value]) => (
                    <EntityRow key={key} label={key.replaceAll("_", " ")} value={value} />
                  ))}
                </div>
              ) : (
                <div className="text-sm text-muted-foreground">
                  No structured entities were extracted from this ticket.
                </div>
              )}
            </CardContent>
          </Card>

          <Card>
            <CardContent className="p-5">
              <div className="mb-3 flex items-center justify-between">
                <div className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">
                  Citations
                </div>
                <span className="text-[11px] text-muted-foreground">{sources.length} sources</span>
              </div>
              <div className="space-y-2">
                {sources.map((source) => (
                  <CitationCard key={source.id} source={source} relevance={source.relevance} />
                ))}
                {!sources.length && (
                  <div className="rounded-md border border-dashed border-border p-4 text-center text-xs text-muted-foreground">
                    Retrieval returned no usable sources for this ticket yet.
                  </div>
                )}
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardContent className="p-5">
              <div className="mb-2 text-xs font-semibold uppercase tracking-wider text-muted-foreground">
                Recommended follow-up
              </div>
              <div className="space-y-1.5">
                {(latestDraft?.missingInfo ?? []).map((item) => (
                  <ActionRow key={item} label={`Ask the customer for ${item.replaceAll("_", " ")}`} />
                ))}
                {firstOpenEscalation && <ActionRow label={`Escalation open: ${firstOpenEscalation.reason}`} />}
                {!latestDraft?.missingInfo?.length && !firstOpenEscalation && (
                  <ActionRow label="Review the draft, approve it, and send the reply when ready." />
                )}
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </AppShell>
  );
}

function Message({
  message,
  customerName,
}: {
  message: { from: "customer" | "agent" | "system"; senderName: string; at: string; text: string };
  customerName: string;
}) {
  const isSystem = message.from === "system";
  const name = message.from === "customer" ? customerName : message.senderName;

  return (
    <div className={`flex gap-3 px-5 py-4 ${isSystem ? "bg-muted/40" : ""}`}>
      <div
        className={`grid h-8 w-8 shrink-0 place-items-center rounded-full text-[11px] font-semibold ${
          isSystem ? "bg-muted text-muted-foreground" : "bg-accent text-accent-foreground"
        }`}
      >
        {isSystem ? "SYS" : name.split(" ").map((part) => part[0]).slice(0, 2).join("")}
      </div>
      <div className="min-w-0 flex-1">
        <div className="flex items-baseline gap-2">
          <span className="text-sm font-semibold">{name}</span>
          <span className="text-[11px] text-muted-foreground">{formatTimestamp(message.at)}</span>
        </div>
        <p className="mt-1 whitespace-pre-line text-sm text-foreground/90">{message.text}</p>
      </div>
    </div>
  );
}

function Field({
  icon: Icon,
  label,
  value,
}: {
  icon: typeof Tag;
  label: string;
  value: string;
}) {
  return (
    <div className="flex items-start gap-2 rounded-md border border-border bg-surface/70 p-3">
      <Icon className="mt-0.5 h-4 w-4 text-muted-foreground" />
      <div className="min-w-0">
        <dt className="text-[11px] uppercase tracking-wide text-muted-foreground">{label}</dt>
        <dd className="mt-0.5 text-sm font-medium">{value}</dd>
      </div>
    </div>
  );
}

function ActionRow({ label }: { label: string }) {
  return <div className="rounded-md border border-border bg-surface px-3 py-2 text-xs font-medium">{label}</div>;
}

function ScorePill({ label, value }: { label: string; value: number }) {
  return (
    <div className="rounded-md border border-border bg-surface/70 px-3 py-2">
      <div className="text-[11px] uppercase tracking-wide text-muted-foreground">{label}</div>
      <div className="mt-1 text-sm font-semibold">{Math.round(value * 100)}%</div>
    </div>
  );
}

function EntityRow({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex items-center justify-between gap-4 rounded-md border border-border bg-surface/70 px-3 py-2 text-xs">
      <span className="capitalize text-muted-foreground">{label}</span>
      <span className="font-mono text-right">{value}</span>
    </div>
  );
}

function SummaryRow({
  label,
  value,
  mono = false,
}: {
  label: string;
  value: string;
  mono?: boolean;
}) {
  return (
    <div className="flex items-center justify-between gap-4">
      <span className="text-muted-foreground">{label}</span>
      <span className={cn("text-right", mono && "font-mono text-xs")}>{value}</span>
    </div>
  );
}

function getDraftText(draft: PersistedTicketDraft | null) {
  return draft?.editedReply ?? draft?.generatedReply ?? "";
}

function inferCustomerPlan(flags: string[]) {
  return flags.includes("vip_customer") ? "enterprise" : "standard";
}

function inferEscalationTeam(flags: string[]) {
  if (flags.includes("security_issue")) return "security";
  if (flags.includes("payment_dispute")) return "billing";
  return "tier-2";
}

function formatMissingInfo(values?: string[]) {
  if (!values?.length) return "None identified";
  return values.map((value) => value.replaceAll("_", " ")).join(", ");
}

function formatTimestamp(value: string) {
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return "--";
  return new Intl.DateTimeFormat("en-US", {
    month: "short",
    day: "numeric",
    hour: "numeric",
    minute: "2-digit",
  }).format(date);
}

function toUiPriority(value: string) {
  const normalized = value.toLowerCase();
  if (normalized === "urgent") return "Urgent" as const;
  if (normalized === "high") return "High" as const;
  if (normalized === "low") return "Low" as const;
  return "Medium" as const;
}

function toUiSentiment(value: string) {
  const normalized = value.toLowerCase();
  if (normalized === "angry") return "Angry" as const;
  if (normalized === "frustrated") return "Frustrated" as const;
  if (normalized === "confused") return "Confused" as const;
  return "Neutral" as const;
}
